//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEasyUI.i18n {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProEasyUI.i18n.es_lang", typeof(es_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias asignadas.
        /// </summary>
        internal static string asig_family_asign {
            get {
                return ResourceManager.GetString("asig.family.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias disponibles.
        /// </summary>
        internal static string asig_family_disp {
            get {
                return ResourceManager.GetString("asig.family.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias del usuario.
        /// </summary>
        internal static string asig_family_title {
            get {
                return ResourceManager.GetString("asig.family.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes asignadas.
        /// </summary>
        internal static string asig_pat_fam_asign {
            get {
                return ResourceManager.GetString("asig.pat.fam.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes disponibles.
        /// </summary>
        internal static string asig_pat_fam_disp {
            get {
                return ResourceManager.GetString("asig.pat.fam.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes de la familia.
        /// </summary>
        internal static string asig_pat_fam_title {
            get {
                return ResourceManager.GetString("asig.pat.fam.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes asignadas.
        /// </summary>
        internal static string asig_patente_asign {
            get {
                return ResourceManager.GetString("asig.patente.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes disponibles.
        /// </summary>
        internal static string asig_patente_disp {
            get {
                return ResourceManager.GetString("asig.patente.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes del usuario.
        /// </summary>
        internal static string asig_patente_title {
            get {
                return ResourceManager.GetString("asig.patente.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos asignados.
        /// </summary>
        internal static string asig_rec_proj_asign {
            get {
                return ResourceManager.GetString("asig.rec.proj.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos disponibles.
        /// </summary>
        internal static string asig_rec_proj_disp {
            get {
                return ResourceManager.GetString("asig.rec.proj.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos del proyecto.
        /// </summary>
        internal static string asig_rec_proj_title {
            get {
                return ResourceManager.GetString("asig.rec.proj.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de volumenes.
        /// </summary>
        internal static string backup_cant {
            get {
                return ResourceManager.GetString("backup.cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string backup_export {
            get {
                return ResourceManager.GetString("backup.export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de destino.
        /// </summary>
        internal static string backup_path {
            get {
                return ResourceManager.GetString("backup.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos.
        /// </summary>
        internal static string connection_db {
            get {
                return ResourceManager.GetString("connection.db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string connection_pass {
            get {
                return ResourceManager.GetString("connection.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string connection_save {
            get {
                return ResourceManager.GetString("connection.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor.
        /// </summary>
        internal static string connection_server {
            get {
                return ResourceManager.GetString("connection.server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string connection_user {
            get {
                return ResourceManager.GetString("connection.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string family_cancel {
            get {
                return ResourceManager.GetString("family.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string family_create {
            get {
                return ResourceManager.GetString("family.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string family_delete {
            get {
                return ResourceManager.GetString("family.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string family_list_name {
            get {
                return ResourceManager.GetString("family.list.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string family_name {
            get {
                return ResourceManager.GetString("family.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar patentes.
        /// </summary>
        internal static string family_patentes {
            get {
                return ResourceManager.GetString("family.patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string family_save {
            get {
                return ResourceManager.GetString("family.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de hs.
        /// </summary>
        internal static string hour_amount {
            get {
                return ResourceManager.GetString("hour.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string hour_cancel {
            get {
                return ResourceManager.GetString("hour.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string hour_create {
            get {
                return ResourceManager.GetString("hour.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string hour_date {
            get {
                return ResourceManager.GetString("hour.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string hour_delete {
            get {
                return ResourceManager.GetString("hour.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas.
        /// </summary>
        internal static string hour_list_amount {
            get {
                return ResourceManager.GetString("hour.list.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string hour_list_date {
            get {
                return ResourceManager.GetString("hour.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string hour_list_project {
            get {
                return ResourceManager.GetString("hour.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string hour_list_task {
            get {
                return ResourceManager.GetString("hour.list.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string hour_project {
            get {
                return ResourceManager.GetString("hour.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string hour_save {
            get {
                return ResourceManager.GetString("hour.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string hour_task {
            get {
                return ResourceManager.GetString("hour.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string log_clean {
            get {
                return ResourceManager.GetString("log.clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string log_level {
            get {
                return ResourceManager.GetString("log.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string log_list_date {
            get {
                return ResourceManager.GetString("log.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string log_list_desc {
            get {
                return ResourceManager.GetString("log.list.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        internal static string log_list_functionality {
            get {
                return ResourceManager.GetString("log.list.functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string log_list_level {
            get {
                return ResourceManager.GetString("log.list.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string log_list_user {
            get {
                return ResourceManager.GetString("log.list.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string log_search {
            get {
                return ResourceManager.GetString("log.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string log_since {
            get {
                return ResourceManager.GetString("log.since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string log_until {
            get {
                return ResourceManager.GetString("log.until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string log_user {
            get {
                return ResourceManager.GetString("log.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar String de conexion.
        /// </summary>
        internal static string login_connection_string {
            get {
                return ResourceManager.GetString("login.connection.string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string login_language {
            get {
                return ResourceManager.GetString("login.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string login_login {
            get {
                return ResourceManager.GetString("login.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string login_pass {
            get {
                return ResourceManager.GetString("login.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string login_user {
            get {
                return ResourceManager.GetString("login.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar backup.
        /// </summary>
        internal static string menu_backup {
            get {
                return ResourceManager.GetString("menu.backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar String de conexión.
        /// </summary>
        internal static string menu_connection_string {
            get {
                return ResourceManager.GetString("menu.connection.string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string menu_families {
            get {
                return ResourceManager.GetString("menu.families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Horas.
        /// </summary>
        internal static string menu_hours {
            get {
                return ResourceManager.GetString("menu.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string menu_language {
            get {
                return ResourceManager.GetString("menu.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string menu_logout {
            get {
                return ResourceManager.GetString("menu.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Bitácora.
        /// </summary>
        internal static string menu_logs {
            get {
                return ResourceManager.GetString("menu.logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string menu_projects {
            get {
                return ResourceManager.GetString("menu.projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de rentabilidad de proyectos.
        /// </summary>
        internal static string menu_report {
            get {
                return ResourceManager.GetString("menu.report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar restore.
        /// </summary>
        internal static string menu_restore {
            get {
                return ResourceManager.GetString("menu.restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        internal static string menu_tasks {
            get {
                return ResourceManager.GetString("menu.tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string menu_users {
            get {
                return ResourceManager.GetString("menu.users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string project_cancel {
            get {
                return ResourceManager.GetString("project.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string project_create {
            get {
                return ResourceManager.GetString("project.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string project_delete {
            get {
                return ResourceManager.GetString("project.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string project_enabled {
            get {
                return ResourceManager.GetString("project.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimadas.
        /// </summary>
        internal static string project_estimated {
            get {
                return ResourceManager.GetString("project.estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insumidas.
        /// </summary>
        internal static string project_insumidas {
            get {
                return ResourceManager.GetString("project.insumidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string project_list_enabled {
            get {
                return ResourceManager.GetString("project.list.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del proyecto.
        /// </summary>
        internal static string project_list_title {
            get {
                return ResourceManager.GetString("project.list.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProEasy.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar recursos.
        /// </summary>
        internal static string project_resources {
            get {
                return ResourceManager.GetString("project.resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string project_save {
            get {
                return ResourceManager.GetString("project.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string project_title {
            get {
                return ResourceManager.GetString("project.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor hora acordado con el cliente.
        /// </summary>
        internal static string project_valor {
            get {
                return ResourceManager.GetString("project.valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string report_clean {
            get {
                return ResourceManager.GetString("report.clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string report_list_date {
            get {
                return ResourceManager.GetString("report.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desvio dinero.
        /// </summary>
        internal static string report_list_desvio_dinero {
            get {
                return ResourceManager.GetString("report.list.desvio.dinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Desvio.
        /// </summary>
        internal static string report_list_desvio_hs {
            get {
                return ResourceManager.GetString("report.list.desvio.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Estimadas.
        /// </summary>
        internal static string report_list_estimated_hs {
            get {
                return ResourceManager.GetString("report.list.estimated.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Insumidas.
        /// </summary>
        internal static string report_list_insumidas_hs {
            get {
                return ResourceManager.GetString("report.list.insumidas.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string report_list_project {
            get {
                return ResourceManager.GetString("report.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string report_list_state {
            get {
                return ResourceManager.GetString("report.list.state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string report_search {
            get {
                return ResourceManager.GetString("report.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string report_since {
            get {
                return ResourceManager.GetString("report.since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string report_until {
            get {
                return ResourceManager.GetString("report.until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        internal static string restore_import {
            get {
                return ResourceManager.GetString("restore.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de origen.
        /// </summary>
        internal static string restore_path {
            get {
                return ResourceManager.GetString("restore.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directorio del backup.
        /// </summary>
        internal static string restore_path_label {
            get {
                return ResourceManager.GetString("restore.path.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string task_cancel {
            get {
                return ResourceManager.GetString("task.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string task_create {
            get {
                return ResourceManager.GetString("task.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string task_delete {
            get {
                return ResourceManager.GetString("task.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string task_description {
            get {
                return ResourceManager.GetString("task.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string task_list_project {
            get {
                return ResourceManager.GetString("task.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string task_list_title {
            get {
                return ResourceManager.GetString("task.list.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string task_project {
            get {
                return ResourceManager.GetString("task.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string task_save {
            get {
                return ResourceManager.GetString("task.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string task_title {
            get {
                return ResourceManager.GetString("task.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string user_cancel {
            get {
                return ResourceManager.GetString("user.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string user_create {
            get {
                return ResourceManager.GetString("user.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string user_delete {
            get {
                return ResourceManager.GetString("user.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad mensual.
        /// </summary>
        internal static string user_disp {
            get {
                return ResourceManager.GetString("user.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string user_enabled {
            get {
                return ResourceManager.GetString("user.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar familia.
        /// </summary>
        internal static string user_families {
            get {
                return ResourceManager.GetString("user.families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar contraseña.
        /// </summary>
        internal static string user_generate_pass {
            get {
                return ResourceManager.GetString("user.generate.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string user_lastname {
            get {
                return ResourceManager.GetString("user.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string user_list_lastname {
            get {
                return ResourceManager.GetString("user.list.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string user_list_name {
            get {
                return ResourceManager.GetString("user.list.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string user_list_state {
            get {
                return ResourceManager.GetString("user.list.state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string user_list_username {
            get {
                return ResourceManager.GetString("user.list.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar patente.
        /// </summary>
        internal static string user_patentes {
            get {
                return ResourceManager.GetString("user.patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string user_save {
            get {
                return ResourceManager.GetString("user.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        internal static string user_unlock {
            get {
                return ResourceManager.GetString("user.unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string user_username {
            get {
                return ResourceManager.GetString("user.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor hora.
        /// </summary>
        internal static string user_valor {
            get {
                return ResourceManager.GetString("user.valor", resourceCulture);
            }
        }
    }
}
