//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProEasyUI.i18n {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class es_lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal es_lang() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProEasyUI.i18n.es_lang", typeof(es_lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias asignadas.
        /// </summary>
        internal static string asig_family_asign {
            get {
                return ResourceManager.GetString("asig.family.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias disponibles.
        /// </summary>
        internal static string asig_family_disp {
            get {
                return ResourceManager.GetString("asig.family.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias del usuario.
        /// </summary>
        internal static string asig_family_title {
            get {
                return ResourceManager.GetString("asig.family.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes asignadas.
        /// </summary>
        internal static string asig_pat_fam_asign {
            get {
                return ResourceManager.GetString("asig.pat.fam.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes disponibles.
        /// </summary>
        internal static string asig_pat_fam_disp {
            get {
                return ResourceManager.GetString("asig.pat.fam.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes de la familia.
        /// </summary>
        internal static string asig_pat_fam_title {
            get {
                return ResourceManager.GetString("asig.pat.fam.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes asignadas.
        /// </summary>
        internal static string asig_patente_asign {
            get {
                return ResourceManager.GetString("asig.patente.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes disponibles.
        /// </summary>
        internal static string asig_patente_disp {
            get {
                return ResourceManager.GetString("asig.patente.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Patentes del usuario.
        /// </summary>
        internal static string asig_patente_title {
            get {
                return ResourceManager.GetString("asig.patente.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos asignados.
        /// </summary>
        internal static string asig_rec_proj_asign {
            get {
                return ResourceManager.GetString("asig.rec.proj.asign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos disponibles.
        /// </summary>
        internal static string asig_rec_proj_disp {
            get {
                return ResourceManager.GetString("asig.rec.proj.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recursos del proyecto.
        /// </summary>
        internal static string asig_rec_proj_title {
            get {
                return ResourceManager.GetString("asig.rec.proj.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una familia para asignar.
        /// </summary>
        internal static string asignacion_familia_usuario_asign_required {
            get {
                return ResourceManager.GetString("asignacion.familia.usuario.asign.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una familia para desasignar.
        /// </summary>
        internal static string asignacion_familia_usuario_remove_required {
            get {
                return ResourceManager.GetString("asignacion.familia.usuario.remove.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una patente para asignar.
        /// </summary>
        internal static string asignacion_patente_familia_asign_required {
            get {
                return ResourceManager.GetString("asignacion.patente.familia.asign.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una patente para desasignar.
        /// </summary>
        internal static string asignacion_patente_familia_remove_required {
            get {
                return ResourceManager.GetString("asignacion.patente.familia.remove.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una patente para asignar.
        /// </summary>
        internal static string asignacion_patente_uduario_asign_required {
            get {
                return ResourceManager.GetString("asignacion.patente.uduario.asign.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar una patente para desasignar.
        /// </summary>
        internal static string asignacion_patente_uduario_remove_required {
            get {
                return ResourceManager.GetString("asignacion.patente.uduario.remove.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un usuario para asignar.
        /// </summary>
        internal static string asignacion_recurso_project_asign_required {
            get {
                return ResourceManager.GetString("asignacion.recurso.project.asign.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe seleccionar un usuario para desasignar.
        /// </summary>
        internal static string asignacion_recurso_project_remove_required {
            get {
                return ResourceManager.GetString("asignacion.recurso.project.remove.required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de volumenes.
        /// </summary>
        internal static string backup_cant {
            get {
                return ResourceManager.GetString("backup.cant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu bkp esta aca y lo copiamos al clipboard: .
        /// </summary>
        internal static string backup_created {
            get {
                return ResourceManager.GetString("backup.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string backup_export {
            get {
                return ResourceManager.GetString("backup.export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de destino.
        /// </summary>
        internal static string backup_path {
            get {
                return ResourceManager.GetString("backup.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indique la cantidad de particiones.
        /// </summary>
        internal static string backup_required_size {
            get {
                return ResourceManager.GetString("backup.required.size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Base de datos.
        /// </summary>
        internal static string connection_db {
            get {
                return ResourceManager.GetString("connection.db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string connection_pass {
            get {
                return ResourceManager.GetString("connection.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string connection_save {
            get {
                return ResourceManager.GetString("connection.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servidor.
        /// </summary>
        internal static string connection_server {
            get {
                return ResourceManager.GetString("connection.server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debera volver a abrir la aplicacion para tomar la nueva configuracion.
        /// </summary>
        internal static string connection_string_saved {
            get {
                return ResourceManager.GetString("connection.string.saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string connection_user {
            get {
                return ResourceManager.GetString("connection.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error general, contacte con el administrador.
        /// </summary>
        internal static string errors_1 {
            get {
                return ResourceManager.GetString("errors.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al generar la contraseña.
        /// </summary>
        internal static string errors_10 {
            get {
                return ResourceManager.GetString("errors.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al ejecutar la consulta.
        /// </summary>
        internal static string errors_100 {
            get {
                return ResourceManager.GetString("errors.100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login incorrecto, chequee los datos.
        /// </summary>
        internal static string errors_1000 {
            get {
                return ResourceManager.GetString("errors.1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No tiene configurada una base de datos.
        /// </summary>
        internal static string errors_1001 {
            get {
                return ResourceManager.GetString("errors.1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar la bitacora.
        /// </summary>
        internal static string errors_105 {
            get {
                return ResourceManager.GetString("errors.105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al verificar la integridad de la base.
        /// </summary>
        internal static string errors_11 {
            get {
                return ResourceManager.GetString("errors.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se encuentra bloqueado.
        /// </summary>
        internal static string errors_12 {
            get {
                return ResourceManager.GetString("errors.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario ya existe.
        /// </summary>
        internal static string errors_13 {
            get {
                return ResourceManager.GetString("errors.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hay patentes que quedaran sin asignacion.
        /// </summary>
        internal static string errors_14 {
            get {
                return ResourceManager.GetString("errors.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Existe mas de un registro.
        /// </summary>
        internal static string errors_15 {
            get {
                return ResourceManager.GetString("errors.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron resultados.
        /// </summary>
        internal static string errors_16 {
            get {
                return ResourceManager.GetString("errors.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar el usuario.
        /// </summary>
        internal static string errors_17 {
            get {
                return ResourceManager.GetString("errors.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una tarea con ese titulo.
        /// </summary>
        internal static string errors_20 {
            get {
                return ResourceManager.GetString("errors.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarea tiene horas cargadas.
        /// </summary>
        internal static string errors_21 {
            get {
                return ResourceManager.GetString("errors.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar la tarea.
        /// </summary>
        internal static string errors_25 {
            get {
                return ResourceManager.GetString("errors.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto ya existe.
        /// </summary>
        internal static string errors_40 {
            get {
                return ResourceManager.GetString("errors.40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto tiene tareas asociadas.
        /// </summary>
        internal static string errors_41 {
            get {
                return ResourceManager.GetString("errors.41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar el proyecto.
        /// </summary>
        internal static string errors_45 {
            get {
                return ResourceManager.GetString("errors.45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Familia existe.
        /// </summary>
        internal static string errors_50 {
            get {
                return ResourceManager.GetString("errors.50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Familia esta asignada a un usuario.
        /// </summary>
        internal static string errors_51 {
            get {
                return ResourceManager.GetString("errors.51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Familia tiene patentes asignadas.
        /// </summary>
        internal static string errors_52 {
            get {
                return ResourceManager.GetString("errors.52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La Familia tiene patentes asignadas.
        /// </summary>
        internal static string errors_53 {
            get {
                return ResourceManager.GetString("errors.53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar la familia.
        /// </summary>
        internal static string errors_55 {
            get {
                return ResourceManager.GetString("errors.55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al crear el bkp.
        /// </summary>
        internal static string errors_60 {
            get {
                return ResourceManager.GetString("errors.60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La patente no tiene otra asignacion.
        /// </summary>
        internal static string errors_70 {
            get {
                return ResourceManager.GetString("errors.70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar la patente.
        /// </summary>
        internal static string errors_75 {
            get {
                return ResourceManager.GetString("errors.75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error al eliminar el digito verificador.
        /// </summary>
        internal static string errors_95 {
            get {
                return ResourceManager.GetString("errors.95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportar.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se exporto correctamente.
        /// </summary>
        internal static string exportado {
            get {
                return ResourceManager.GetString("exportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string family_cancel {
            get {
                return ResourceManager.GetString("family.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string family_create {
            get {
                return ResourceManager.GetString("family.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La familia se creo correctamente.
        /// </summary>
        internal static string family_created {
            get {
                return ResourceManager.GetString("family.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string family_delete {
            get {
                return ResourceManager.GetString("family.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La familia se elimino correctamente.
        /// </summary>
        internal static string family_deleted {
            get {
                return ResourceManager.GetString("family.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string family_list_name {
            get {
                return ResourceManager.GetString("family.list.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string family_name {
            get {
                return ResourceManager.GetString("family.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar patentes.
        /// </summary>
        internal static string family_patentes {
            get {
                return ResourceManager.GetString("family.patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string family_required_name {
            get {
                return ResourceManager.GetString("family.required.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string family_save {
            get {
                return ResourceManager.GetString("family.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La familia se actualizo correctamente.
        /// </summary>
        internal static string family_updated {
            get {
                return ResourceManager.GetString("family.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las horas se registraron correctamente.
        /// </summary>
        internal static string hora_created {
            get {
                return ResourceManager.GetString("hora.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se cargaron las horas.
        /// </summary>
        internal static string horas_created {
            get {
                return ResourceManager.GetString("horas.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se eliminaron las horas cargadas.
        /// </summary>
        internal static string horas_deleted {
            get {
                return ResourceManager.GetString("horas.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto es requerido.
        /// </summary>
        internal static string horas_required_project {
            get {
                return ResourceManager.GetString("horas.required.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha desde es requerida.
        /// </summary>
        internal static string horas_required_since {
            get {
                return ResourceManager.GetString("horas.required.since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarea es requerida.
        /// </summary>
        internal static string horas_required_task {
            get {
                return ResourceManager.GetString("horas.required.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha hasta es requerida.
        /// </summary>
        internal static string horas_required_until {
            get {
                return ResourceManager.GetString("horas.required.until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se actualizaron las horas.
        /// </summary>
        internal static string horas_updated {
            get {
                return ResourceManager.GetString("horas.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cantidad de hs.
        /// </summary>
        internal static string hour_amount {
            get {
                return ResourceManager.GetString("hour.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string hour_cancel {
            get {
                return ResourceManager.GetString("hour.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string hour_create {
            get {
                return ResourceManager.GetString("hour.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string hour_date {
            get {
                return ResourceManager.GetString("hour.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string hour_delete {
            get {
                return ResourceManager.GetString("hour.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horas.
        /// </summary>
        internal static string hour_list_amount {
            get {
                return ResourceManager.GetString("hour.list.amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string hour_list_date {
            get {
                return ResourceManager.GetString("hour.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string hour_list_project {
            get {
                return ResourceManager.GetString("hour.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string hour_list_task {
            get {
                return ResourceManager.GetString("hour.list.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string hour_project {
            get {
                return ResourceManager.GetString("hour.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string hour_save {
            get {
                return ResourceManager.GetString("hour.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarea.
        /// </summary>
        internal static string hour_task {
            get {
                return ResourceManager.GetString("hour.task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string log_clean {
            get {
                return ResourceManager.GetString("log.clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string log_level {
            get {
                return ResourceManager.GetString("log.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string log_list_date {
            get {
                return ResourceManager.GetString("log.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string log_list_desc {
            get {
                return ResourceManager.GetString("log.list.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidad.
        /// </summary>
        internal static string log_list_functionality {
            get {
                return ResourceManager.GetString("log.list.functionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Criticidad.
        /// </summary>
        internal static string log_list_level {
            get {
                return ResourceManager.GetString("log.list.level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string log_list_user {
            get {
                return ResourceManager.GetString("log.list.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string log_search {
            get {
                return ResourceManager.GetString("log.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string log_since {
            get {
                return ResourceManager.GetString("log.since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string log_until {
            get {
                return ResourceManager.GetString("log.until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string log_user {
            get {
                return ResourceManager.GetString("log.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar String de conexion.
        /// </summary>
        internal static string login_connection_string {
            get {
                return ResourceManager.GetString("login.connection.string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string login_language {
            get {
                return ResourceManager.GetString("login.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        internal static string login_login {
            get {
                return ResourceManager.GetString("login.login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string login_pass {
            get {
                return ResourceManager.GetString("login.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string login_user {
            get {
                return ResourceManager.GetString("login.user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar backup.
        /// </summary>
        internal static string menu_backup {
            get {
                return ResourceManager.GetString("menu.backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar String de conexión.
        /// </summary>
        internal static string menu_connection_string {
            get {
                return ResourceManager.GetString("menu.connection.string", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familias.
        /// </summary>
        internal static string menu_families {
            get {
                return ResourceManager.GetString("menu.families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga de Horas.
        /// </summary>
        internal static string menu_hours {
            get {
                return ResourceManager.GetString("menu.hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string menu_language {
            get {
                return ResourceManager.GetString("menu.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        internal static string menu_logout {
            get {
                return ResourceManager.GetString("menu.logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consultar Bitácora.
        /// </summary>
        internal static string menu_logs {
            get {
                return ResourceManager.GetString("menu.logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyectos.
        /// </summary>
        internal static string menu_projects {
            get {
                return ResourceManager.GetString("menu.projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reporte de rentabilidad de proyectos.
        /// </summary>
        internal static string menu_report {
            get {
                return ResourceManager.GetString("menu.report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Realizar restore.
        /// </summary>
        internal static string menu_restore {
            get {
                return ResourceManager.GetString("menu.restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas.
        /// </summary>
        internal static string menu_tasks {
            get {
                return ResourceManager.GetString("menu.tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string menu_users {
            get {
                return ResourceManager.GetString("menu.users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string project_cancel {
            get {
                return ResourceManager.GetString("project.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string project_create {
            get {
                return ResourceManager.GetString("project.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto se creo correctamente.
        /// </summary>
        internal static string project_created {
            get {
                return ResourceManager.GetString("project.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string project_delete {
            get {
                return ResourceManager.GetString("project.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto se elimino correctamente.
        /// </summary>
        internal static string project_deleted {
            get {
                return ResourceManager.GetString("project.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string project_enabled {
            get {
                return ResourceManager.GetString("project.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estimadas.
        /// </summary>
        internal static string project_estimated {
            get {
                return ResourceManager.GetString("project.estimated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insumidas.
        /// </summary>
        internal static string project_insumidas {
            get {
                return ResourceManager.GetString("project.insumidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string project_list_enabled {
            get {
                return ResourceManager.GetString("project.list.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del proyecto.
        /// </summary>
        internal static string project_list_title {
            get {
                return ResourceManager.GetString("project.list.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ProEasy.
        /// </summary>
        internal static string project_name {
            get {
                return ResourceManager.GetString("project.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las horas estimadas son requeridas.
        /// </summary>
        internal static string project_required_horas {
            get {
                return ResourceManager.GetString("project.required.horas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string project_required_name {
            get {
                return ResourceManager.GetString("project.required.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor hora es requerido.
        /// </summary>
        internal static string project_required_salary {
            get {
                return ResourceManager.GetString("project.required.salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar recursos.
        /// </summary>
        internal static string project_resources {
            get {
                return ResourceManager.GetString("project.resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string project_save {
            get {
                return ResourceManager.GetString("project.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string project_title {
            get {
                return ResourceManager.GetString("project.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto se actualizo correctamente.
        /// </summary>
        internal static string project_updated {
            get {
                return ResourceManager.GetString("project.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor hora acordado con el cliente.
        /// </summary>
        internal static string project_valor {
            get {
                return ResourceManager.GetString("project.valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string report_clean {
            get {
                return ResourceManager.GetString("report.clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string report_list_date {
            get {
                return ResourceManager.GetString("report.list.date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desvio dinero.
        /// </summary>
        internal static string report_list_desvio_dinero {
            get {
                return ResourceManager.GetString("report.list.desvio.dinero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Desvio.
        /// </summary>
        internal static string report_list_desvio_hs {
            get {
                return ResourceManager.GetString("report.list.desvio.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Estimadas.
        /// </summary>
        internal static string report_list_estimated_hs {
            get {
                return ResourceManager.GetString("report.list.estimated.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hs Insumidas.
        /// </summary>
        internal static string report_list_insumidas_hs {
            get {
                return ResourceManager.GetString("report.list.insumidas.hs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string report_list_project {
            get {
                return ResourceManager.GetString("report.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string report_list_state {
            get {
                return ResourceManager.GetString("report.list.state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        internal static string report_search {
            get {
                return ResourceManager.GetString("report.search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desde.
        /// </summary>
        internal static string report_since {
            get {
                return ResourceManager.GetString("report.since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hasta.
        /// </summary>
        internal static string report_until {
            get {
                return ResourceManager.GetString("report.until", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        internal static string restore_import {
            get {
                return ResourceManager.GetString("restore.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de origen.
        /// </summary>
        internal static string restore_path {
            get {
                return ResourceManager.GetString("restore.path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Directorio del backup.
        /// </summary>
        internal static string restore_path_label {
            get {
                return ResourceManager.GetString("restore.path.label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se restauro la base correctamente.
        /// </summary>
        internal static string restore_sucess {
            get {
                return ResourceManager.GetString("restore.sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string task_cancel {
            get {
                return ResourceManager.GetString("task.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string task_create {
            get {
                return ResourceManager.GetString("task.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarea se creo correctamente.
        /// </summary>
        internal static string task_created {
            get {
                return ResourceManager.GetString("task.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string task_delete {
            get {
                return ResourceManager.GetString("task.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarea se elimino correctamente.
        /// </summary>
        internal static string task_deleted {
            get {
                return ResourceManager.GetString("task.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripcion.
        /// </summary>
        internal static string task_description {
            get {
                return ResourceManager.GetString("task.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string task_list_project {
            get {
                return ResourceManager.GetString("task.list.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string task_list_title {
            get {
                return ResourceManager.GetString("task.list.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proyecto.
        /// </summary>
        internal static string task_project {
            get {
                return ResourceManager.GetString("task.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripcion es requerida.
        /// </summary>
        internal static string task_required_description {
            get {
                return ResourceManager.GetString("task.required.description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El proyecto es requerido.
        /// </summary>
        internal static string task_required_project {
            get {
                return ResourceManager.GetString("task.required.project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El titulo es requerido.
        /// </summary>
        internal static string task_required_title {
            get {
                return ResourceManager.GetString("task.required.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string task_save {
            get {
                return ResourceManager.GetString("task.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo.
        /// </summary>
        internal static string task_title {
            get {
                return ResourceManager.GetString("task.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La tarea se actualizo correctamente.
        /// </summary>
        internal static string task_updated {
            get {
                return ResourceManager.GetString("task.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string user_cancel {
            get {
                return ResourceManager.GetString("user.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear.
        /// </summary>
        internal static string user_create {
            get {
                return ResourceManager.GetString("user.create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario fue creado.
        /// </summary>
        internal static string user_created {
            get {
                return ResourceManager.GetString("user.created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string user_delete {
            get {
                return ResourceManager.GetString("user.delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se elimino correctamente.
        /// </summary>
        internal static string user_deleted {
            get {
                return ResourceManager.GetString("user.deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibilidad mensual.
        /// </summary>
        internal static string user_disp {
            get {
                return ResourceManager.GetString("user.disp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        internal static string user_email {
            get {
                return ResourceManager.GetString("user.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilitado.
        /// </summary>
        internal static string user_enabled {
            get {
                return ResourceManager.GetString("user.enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar familia.
        /// </summary>
        internal static string user_families {
            get {
                return ResourceManager.GetString("user.families", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generar contraseña.
        /// </summary>
        internal static string user_generate_pass {
            get {
                return ResourceManager.GetString("user.generate.pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string user_lastname {
            get {
                return ResourceManager.GetString("user.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido.
        /// </summary>
        internal static string user_list_lastname {
            get {
                return ResourceManager.GetString("user.list.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string user_list_name {
            get {
                return ResourceManager.GetString("user.list.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado.
        /// </summary>
        internal static string user_list_state {
            get {
                return ResourceManager.GetString("user.list.state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string user_list_username {
            get {
                return ResourceManager.GetString("user.list.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string user_name {
            get {
                return ResourceManager.GetString("user.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se reestablecio la contraseña del usuario.
        /// </summary>
        internal static string user_pass_reseted {
            get {
                return ResourceManager.GetString("user.pass.reseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignar patente.
        /// </summary>
        internal static string user_patentes {
            get {
                return ResourceManager.GetString("user.patentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La disponibilidad mensual es requerida.
        /// </summary>
        internal static string user_required_availability {
            get {
                return ResourceManager.GetString("user.required.availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email es requerido.
        /// </summary>
        internal static string user_required_email {
            get {
                return ResourceManager.GetString("user.required.email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El apellido es requerido.
        /// </summary>
        internal static string user_required_lastname {
            get {
                return ResourceManager.GetString("user.required.lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre es requerido.
        /// </summary>
        internal static string user_required_name {
            get {
                return ResourceManager.GetString("user.required.name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor hora es requerido.
        /// </summary>
        internal static string user_required_salary {
            get {
                return ResourceManager.GetString("user.required.salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se desbloqueo el usuario.
        /// </summary>
        internal static string user_required_unlocked {
            get {
                return ResourceManager.GetString("user.required.unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario es requerido.
        /// </summary>
        internal static string user_required_username {
            get {
                return ResourceManager.GetString("user.required.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string user_save {
            get {
                return ResourceManager.GetString("user.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desbloquear.
        /// </summary>
        internal static string user_unlock {
            get {
                return ResourceManager.GetString("user.unlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario se actualizo correctamente.
        /// </summary>
        internal static string user_updated {
            get {
                return ResourceManager.GetString("user.updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        internal static string user_username {
            get {
                return ResourceManager.GetString("user.username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Valor hora.
        /// </summary>
        internal static string user_valor {
            get {
                return ResourceManager.GetString("user.valor", resourceCulture);
            }
        }
    }
}
